In [1]:
import numpy as np

# Create two matrices
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]


In [2]:
addition = A + B
print("Matrix Addition:")
print(addition)

Matrix Addition:
[[ 6  8]
 [10 12]]


In [3]:
subtraction = A - B
print("Matrix Subtraction:")
print(subtraction)

Matrix Subtraction:
[[-4 -4]
 [-4 -4]]


In [4]:
multiplication = np.dot(A, B)
print("Matrix Multiplication:")
print(multiplication)

Matrix Multiplication:
[[19 22]
 [43 50]]


In [5]:
print("Transpose of Matrix A:")
print(A.T)

print("\nTranspose of Matrix B:")
print(B.T)

Transpose of Matrix A:
[[1 3]
 [2 4]]

Transpose of Matrix B:
[[5 7]
 [6 8]]
